config/routes.rb
Bridalka::Application.routes.draw do
  
  devise_for :users
  
  resources :tags
  
  resources :posts do
    resources :elements
    resources :images #, :controller => "elements"
    resources :videos #, :controller => "elements"  
  end

  resources :uploads

  root :to => 'tags#index'
  

end

app/models/element.rb
class Element < ActiveRecord::Base
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  
  before_filter :get_post

  def get_post
    @post = Post.find(params[:post_id])
  end
  
  # GET /elements
  # GET /elements.xml
  def index
    @elements = @post.elements.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @elements }
    end
  end

  # GET /elements/1
  # GET /elements/1.xml
  def show
    @element = @post.elements.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @element }
    end
  end

  # GET /elements/new
  # GET /elements/new.xml
  def new
    @element = @post.elements.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @element }
    end
  end

  # GET /elements/1/edit
  def edit
    @element = @post.element.find(params[:id])
  end

  # POST /elements
  # POST /elements.xml
  def create
    @element = @post.element.new(params[:element])

    respond_to do |format|
      if @element.save
        format.html { redirect_to([@post,@element], :notice => 'Element was successfully created.') }
        format.xml  { render :xml => @element, :status => :created, :location => @element }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @element.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /elements/1
  # PUT /elements/1.xml
  def update
    @element = @post.element.find(params[:id])

    respond_to do |format|
      if @element.update_attributes(params[:element])
        format.html { redirect_to(@element, :notice => 'Element was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @element.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /elements/1
  # DELETE /elements/1.xml
  def destroy
    @element = @post.element.find(params[:id])
    @element.destroy

    respond_to do |format|
      format.html { redirect_to(elements_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/views/elements/_form.html.erb
  <div class="group">
    <%= f.label :post_id, t("activerecord.attributes.element.post_id", :default => "Post"), :class => :label %>
    <%= f.text_field :post_id, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :description, t("activerecord.attributes.element.description", :default => "Description"), :class => :label %>
    <%= f.text_area :description, :class => 'text_area' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :path, t("activerecord.attributes.element.path", :default => "Path"), :class => :label %>
    <%= f.text_field :path, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :filename, t("activerecord.attributes.element.filename", :default => "Filename"), :class => :label %>
    <%= f.text_field :filename, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :content_type, t("activerecord.attributes.element.content_type", :default => "Content type"), :class => :label %>
    <%= f.text_field :content_type, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :width, t("activerecord.attributes.element.width", :default => "Width"), :class => :label %>
    <%= f.text_field :width, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :height, t("activerecord.attributes.element.height", :default => "Height"), :class => :label %>
    <%= f.text_field :height, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :type, t("activerecord.attributes.element.type", :default => "Type"), :class => :label %>
    <%= f.text_field :type, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :element_file_name, t("activerecord.attributes.element.element_file_name", :default => "Element file name"), :class => :label %>
    <%= f.text_field :element_file_name, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :element_content_type, t("activerecord.attributes.element.element_content_type", :default => "Element content type"), :class => :label %>
    <%= f.text_field :element_content_type, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :element_file_size, t("activerecord.attributes.element.element_file_size", :default => "Element file size"), :class => :label %>
    <%= f.text_field :element_file_size, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :element_updated_at, t("activerecord.attributes.element.element_updated_at", :default => "Element updated at"), :class => :label %>
    <%= f.datetime_select :element_updated_at, :class => 'datetime_select' %>
    <span class="description">Ex: a simple text</span>
  </div>
        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), elements_path, :class => "text_button_padding link_button" %>
</div>

app/views/elements/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", elements_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_element_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_element_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Element</h2>
    <div class="inner">
      <%= form_for @element, :url => element_path(@element), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/elements/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", elements_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_element_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Elements</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.element.post_id", :default => t("activerecord.labels.post_id", :default => "Post_id")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @elements.each do |element| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= element.id %>
          </td>
                    <td>
            <%= link_to element.post_id, element_path(element) %>
          </td>
                    <td>
            <%= element.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", element_path(element) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_element_path(element) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", element_path(element), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/elements/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", elements_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_element_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Element</h2>
    <div class="inner">
      <%= form_for :element, :url => elements_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/elements/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", elements_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_element_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", element_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.element.post_id", :default => t("activerecord.labels.post_id", :default => "Post")) %>:</b>
          <%= @element.post_id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.element.description", :default => t("activerecord.labels.description", :default => "Description")) %>:</b>
          <%= @element.description %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.element.path", :default => t("activerecord.labels.path", :default => "Path")) %>:</b>
          <%= @element.path %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.element.filename", :default => t("activerecord.labels.filename", :default => "Filename")) %>:</b>
          <%= @element.filename %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.element.content_type", :default => t("activerecord.labels.content_type", :default => "Content type")) %>:</b>
          <%= @element.content_type %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.element.width", :default => t("activerecord.labels.width", :default => "Width")) %>:</b>
          <%= @element.width %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.element.height", :default => t("activerecord.labels.height", :default => "Height")) %>:</b>
          <%= @element.height %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.element.type", :default => t("activerecord.labels.type", :default => "Type")) %>:</b>
          <%= @element.type %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.element.element_file_name", :default => t("activerecord.labels.element_file_name", :default => "Element file name")) %>:</b>
          <%= @element.element_file_name %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.element.element_content_type", :default => t("activerecord.labels.element_content_type", :default => "Element content type")) %>:</b>
          <%= @element.element_content_type %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.element.element_file_size", :default => t("activerecord.labels.element_file_size", :default => "Element file size")) %>:</b>
          <%= @element.element_file_size %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.element.element_updated_at", :default => t("activerecord.labels.element_updated_at", :default => "Element updated at")) %>:</b>
          <%= @element.element_updated_at %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_element_path(@element), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), element_path(@element), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>