config/routes.rb
Bridalka::Application.routes.draw do
  
  devise_for :users
  
  resources :tags
  
  resources :posts do
    resources :elements
    resources :images #, :controller => "elements"
    resources :videos #, :controller => "elements"  
  end

  resources :uploads

  root :to => 'tags#index'
  

end

app/models/video.rb
class Video < Element
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  # GET /videos
  # GET /videos.xml
  def index
    @videos = Video.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.xml
  def show
    @video = Video.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @video }
    end
  end

  # GET /videos/new
  # GET /videos/new.xml
  def new
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.xml
  def create
    @video = Video.new(params[:video])

    respond_to do |format|
      if @video.save
        format.html { redirect_to(@video, :notice => 'Video was successfully created.') }
        format.xml  { render :xml => @video, :status => :created, :location => @video }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @video.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.xml
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to(@video, :notice => 'Video was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @video.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.xml
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to(videos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
  <div class="group">
    <%= f.label :post_id, t("activerecord.attributes.video.post_id", :default => "Post"), :class => :label %>
    <%= f.text_field :post_id, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :description, t("activerecord.attributes.video.description", :default => "Description"), :class => :label %>
    <%= f.text_area :description, :class => 'text_area' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :path, t("activerecord.attributes.video.path", :default => "Path"), :class => :label %>
    <%= f.text_field :path, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :filename, t("activerecord.attributes.video.filename", :default => "Filename"), :class => :label %>
    <%= f.text_field :filename, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :content_type, t("activerecord.attributes.video.content_type", :default => "Content type"), :class => :label %>
    <%= f.text_field :content_type, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :width, t("activerecord.attributes.video.width", :default => "Width"), :class => :label %>
    <%= f.text_field :width, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :height, t("activerecord.attributes.video.height", :default => "Height"), :class => :label %>
    <%= f.text_field :height, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :type, t("activerecord.attributes.video.type", :default => "Type"), :class => :label %>
    <%= f.text_field :type, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :element_file_name, t("activerecord.attributes.video.element_file_name", :default => "Element file name"), :class => :label %>
    <%= f.text_field :element_file_name, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :element_content_type, t("activerecord.attributes.video.element_content_type", :default => "Element content type"), :class => :label %>
    <%= f.text_field :element_content_type, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :element_file_size, t("activerecord.attributes.video.element_file_size", :default => "Element file size"), :class => :label %>
    <%= f.text_field :element_file_size, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :element_updated_at, t("activerecord.attributes.video.element_updated_at", :default => "Element updated at"), :class => :label %>
    <%= f.datetime_select :element_updated_at, :class => 'datetime_select' %>
    <span class="description">Ex: a simple text</span>
  </div>
        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), videos_path, :class => "text_button_padding link_button" %>
</div>

app/views/videos/_sidebar.html.erb
<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/videos/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", videos_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_video_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_video_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Video</h2>
    <div class="inner">
      <%= form_for @video, :url => video_path(@video), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/videos/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", videos_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_video_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Videos</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.video.post_id", :default => t("activerecord.labels.post_id", :default => "Post_id")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @videos.each do |video| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= video.id %>
          </td>
                    <td>
            <%= link_to video.post_id, video_path(video) %>
          </td>
                    <td>
            <%= video.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", video_path(video) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_video_path(video) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", video_path(video), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/videos/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", videos_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_video_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Video</h2>
    <div class="inner">
      <%= form_for :video, :url => videos_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/videos/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", videos_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_video_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", video_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.video.post_id", :default => t("activerecord.labels.post_id", :default => "Post")) %>:</b>
          <%= @video.post_id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.video.description", :default => t("activerecord.labels.description", :default => "Description")) %>:</b>
          <%= @video.description %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.video.path", :default => t("activerecord.labels.path", :default => "Path")) %>:</b>
          <%= @video.path %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.video.filename", :default => t("activerecord.labels.filename", :default => "Filename")) %>:</b>
          <%= @video.filename %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.video.content_type", :default => t("activerecord.labels.content_type", :default => "Content type")) %>:</b>
          <%= @video.content_type %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.video.width", :default => t("activerecord.labels.width", :default => "Width")) %>:</b>
          <%= @video.width %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.video.height", :default => t("activerecord.labels.height", :default => "Height")) %>:</b>
          <%= @video.height %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.video.type", :default => t("activerecord.labels.type", :default => "Type")) %>:</b>
          <%= @video.type %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.video.element_file_name", :default => t("activerecord.labels.element_file_name", :default => "Element file name")) %>:</b>
          <%= @video.element_file_name %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.video.element_content_type", :default => t("activerecord.labels.element_content_type", :default => "Element content type")) %>:</b>
          <%= @video.element_content_type %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.video.element_file_size", :default => t("activerecord.labels.element_file_size", :default => "Element file size")) %>:</b>
          <%= @video.element_file_size %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.video.element_updated_at", :default => t("activerecord.labels.element_updated_at", :default => "Element updated at")) %>:</b>
          <%= @video.element_updated_at %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_video_path(@video), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), video_path(@video), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>