config/routes.rb
Bridalka::Application.routes.draw do
  
  devise_for :users
  
  resources :tags
  
  resources :posts do
    resources :elements
    resources :images #, :controller => "elements"
    resources :videos #, :controller => "elements"  
  end

  resources :uploads

  root :to => 'tags#index'
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_and_belongs_to_many :tags
  has_many :elements
  has_many :images
  has_many :videos
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    puts "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    puts params[:id]
    puts "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    @post = Post.find(params[:id])
    
    p @post
    puts "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new
    @post.save
    @post.title = "Post #{@post.id}"
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
      format.js
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => [@tag, @post] }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    params[:post][:tag_ids]||=[]
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
  <div class="group">
    <%= f.label :title, t("activerecord.attributes.post.title", :default => "Title"), :class => :label %>
    <%= f.text_field :title, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>
 <div class="group">
   <% for tag in Tag.all %>
    <div>
      <%= check_box_tag "post[tag_ids][]", tag.id, @post.tags.include?(tag) %>
      <%= tag.name %>
    </div>
   <% end %>
 </div>

 <div class="group">
   <div id="elements">
   </div>
 </div>
 <div class="group">
   <div id="new_elements">
     <%= link_to "Add Images", new_post_image_url(@post), :id => "add_images" %>
   </div>
 </div>
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), posts_path, :class => "text_button_padding link_button" %>
</div>

app/views/posts/_post.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= post.title %>
<!-- remove this later -->
  <% render post.elements.all %>
  <% prev_type = "" %>
  <% tCount = 0 %>
  <% post.elements.each do |elem| %>
    <% if elem.type.eql?(prev_type) == false %>
      <% tCount = tCount + 1 %>

    <% end %>
    <%= render elem, {:post_id => post.id, :groupNumber => tCount} %>
    <% prev_type = elem.type%>
  <% end %>
</p>

app/views/posts/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", posts_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_post_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_post_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Post</h2>
    <div class="inner">
      <%= form_for @post, :url => post_path(@post), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/posts/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", posts_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_post_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Posts</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.post.title", :default => t("activerecord.labels.title", :default => "Title")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @posts.each do |post| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= post.id %>
          </td>
                    <td>
            <%= link_to post.title, post_path(post) %>
          </td>
                    <td>
            <%= post.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", post_path(post) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_post_path(post) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", post_path(post), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/posts/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <!--<li class="first">< link_to "#{t("web-app-theme.list", :default => "List")}", posts_path  ></li>
      <li class="active">< link_to "#{t("web-app-theme.new", :default => "New")}", new_post_path ></li>-->
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Post</h2>
    <div class="inner">
      <%= form_for @post, :url => post_path(@post), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/posts/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", posts_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_post_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", post_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.post.title", :default => t("activerecord.labels.title", :default => "Title")) %>:</b>
          <%= @post.title %>
          <% prev_type = "" %>
          <% tCount = 0 %>
          <% @post.elements.each do |elem| %>
            <% if elem.type.eql?(prev_type) == false %>
              <% tCount = tCount + 1 %>
            <% end %>
            <%= render elem, {:post_id => @post.id, :groupNumber => tCount} %>
            <% prev_type = elem.type%>
          <% end %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_post_path(@post), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), post_path(@post), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>